/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bsrtu.bankingapp;

import java.awt.Color;

/**
 *
 * @author Gab
 */
public class AccountPage extends javax.swing.JFrame {

    /**
     * Creates new form AccountPage
     */
    public AccountPage() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Border = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        CardsPanel = new javax.swing.JPanel();
        CardsLabel = new javax.swing.JLabel();
        LinkedCards = new javax.swing.JPanel();
        LinkedCardsLabel = new javax.swing.JLabel();
        ManageCards = new javax.swing.JButton();
        TransactionHistory = new javax.swing.JButton();
        BalanceBackground = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        BalancePanel = new javax.swing.JPanel();
        BalanceLabel = new javax.swing.JLabel();
        Balance = new javax.swing.JLabel();
        TransferMoney = new javax.swing.JButton();
        Settings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Border.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CardsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CardsLabel.setBackground(new java.awt.Color(153, 153, 153));
        CardsLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        CardsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CardsLabel.setText("Your Debit/Credit Cards");

        LinkedCards.setBackground(new java.awt.Color(153, 153, 153));
        LinkedCards.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LinkedCardsLabel.setBackground(new java.awt.Color(102, 153, 255));
        LinkedCardsLabel.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        LinkedCardsLabel.setForeground(new java.awt.Color(255, 255, 255));
        LinkedCardsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LinkedCardsLabel.setText("You have no linked cards.");

        javax.swing.GroupLayout LinkedCardsLayout = new javax.swing.GroupLayout(LinkedCards);
        LinkedCards.setLayout(LinkedCardsLayout);
        LinkedCardsLayout.setHorizontalGroup(
            LinkedCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LinkedCardsLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(LinkedCardsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LinkedCardsLayout.setVerticalGroup(
            LinkedCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LinkedCardsLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(LinkedCardsLabel)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        ManageCards.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        ManageCards.setText("Manage Cards");
        ManageCards.setContentAreaFilled(false);
        ManageCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCardsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CardsPanelLayout = new javax.swing.GroupLayout(CardsPanel);
        CardsPanel.setLayout(CardsPanelLayout);
        CardsPanelLayout.setHorizontalGroup(
            CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LinkedCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CardsPanelLayout.createSequentialGroup()
                        .addComponent(CardsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ManageCards)))
                .addContainerGap())
        );
        CardsPanelLayout.setVerticalGroup(
            CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardsLabel)
                    .addComponent(ManageCards))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LinkedCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TransactionHistory.setBackground(new java.awt.Color(204, 255, 255));
        TransactionHistory.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        TransactionHistory.setForeground(new java.awt.Color(0, 51, 51));
        TransactionHistory.setText("Transaction History");

        BalanceBackground.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        NameLabel.setBackground(new java.awt.Color(153, 153, 153));
        NameLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NameLabel.setText("Welcome, Placeholder Name");

        BalancePanel.setBackground(new java.awt.Color(102, 153, 255));
        BalancePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BalanceLabel.setBackground(new java.awt.Color(102, 153, 255));
        BalanceLabel.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        BalanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        BalanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BalanceLabel.setText("Your Balance is :");

        Balance.setBackground(new java.awt.Color(102, 153, 255));
        Balance.setFont(new java.awt.Font("Product Sans", 1, 36)); // NOI18N
        Balance.setForeground(new java.awt.Color(255, 255, 255));
        Balance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Balance.setText("$35.00");

        TransferMoney.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        TransferMoney.setForeground(new java.awt.Color(102, 153, 255));
        TransferMoney.setText("Transfer Money");
        TransferMoney.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TransferMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferMoneyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BalancePanelLayout = new javax.swing.GroupLayout(BalancePanel);
        BalancePanel.setLayout(BalancePanelLayout);
        BalancePanelLayout.setHorizontalGroup(
            BalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BalancePanelLayout.createSequentialGroup()
                .addGroup(BalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BalancePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TransferMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BalancePanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(BalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        BalancePanelLayout.setVerticalGroup(
            BalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BalancePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BalanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(TransferMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Settings.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        Settings.setText(" Settings ");
        Settings.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Settings.setContentAreaFilled(false);
        Settings.setOpaque(true);
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
        });
        Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BalanceBackgroundLayout = new javax.swing.GroupLayout(BalanceBackground);
        BalanceBackground.setLayout(BalanceBackgroundLayout);
        BalanceBackgroundLayout.setHorizontalGroup(
            BalanceBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BalanceBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BalanceBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BalanceBackgroundLayout.createSequentialGroup()
                        .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                        .addGap(61, 61, 61)
                        .addComponent(Settings))
                    .addComponent(BalancePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BalanceBackgroundLayout.setVerticalGroup(
            BalanceBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BalanceBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BalanceBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Settings, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BalancePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CardsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TransactionHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BalanceBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BalanceBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CardsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TransactionHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout BorderLayout = new javax.swing.GroupLayout(Border);
        Border.setLayout(BorderLayout);
        BorderLayout.setHorizontalGroup(
            BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BorderLayout.setVerticalGroup(
            BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Border, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Border, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCardsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageCardsActionPerformed

    private void TransferMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransferMoneyActionPerformed

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked
        Settings settings = new Settings();
        settings.setVisible(true);
        settings.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_SettingsMouseClicked

    private void SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Balance;
    private javax.swing.JPanel BalanceBackground;
    private javax.swing.JLabel BalanceLabel;
    private javax.swing.JPanel BalancePanel;
    private javax.swing.JPanel Border;
    private javax.swing.JLabel CardsLabel;
    private javax.swing.JPanel CardsPanel;
    private javax.swing.JPanel LinkedCards;
    private javax.swing.JLabel LinkedCardsLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton ManageCards;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton Settings;
    private javax.swing.JButton TransactionHistory;
    private javax.swing.JButton TransferMoney;
    // End of variables declaration//GEN-END:variables
}
