package bsrtu.bankingapp;

import java.awt.Color;
import javax.swing.*;
import javax.swing.text.AbstractDocument;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gab
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MaritalStatusButtons = new javax.swing.ButtonGroup();
        Border1 = new javax.swing.JPanel();
        Border2 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        CreateAccount = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        Username = new javax.swing.JTextField();
        FullName = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        FullNameLabel = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        Age = new javax.swing.JTextField();
        Nationality = new javax.swing.JTextField();
        AgeLabel = new javax.swing.JLabel();
        NationalityLabel = new javax.swing.JLabel();
        BirthdayDay = new javax.swing.JComboBox<>();
        BirthdayMonth = new javax.swing.JComboBox<>();
        BirthdayYear = new javax.swing.JComboBox<>();
        PhoneNumber = new javax.swing.JTextField();
        PhoneNumberLabel = new javax.swing.JLabel();
        BirthdayLabel = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        EmailAddress = new javax.swing.JTextField();
        HomeAddress = new javax.swing.JTextField();
        EmailAddressLabel = new javax.swing.JLabel();
        HomeAddressLabel = new javax.swing.JLabel();
        MaritalStatusLabel = new javax.swing.JLabel();
        ButtonSingle = new javax.swing.JRadioButton();
        ButtonMarried = new javax.swing.JRadioButton();
        ButtonWidowed = new javax.swing.JRadioButton();
        LogIn = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Border1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Border2.setBackground(new java.awt.Color(255, 255, 255));
        Border2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Header.setBackground(new java.awt.Color(102, 153, 255));
        Header.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CreateAccount.setBackground(new java.awt.Color(102, 153, 255));
        CreateAccount.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        CreateAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateAccount.setText("Create Account");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ((AbstractDocument) Username.getDocument()).setDocumentFilter(new MaxLengthDocumentFilter(20));
        Username.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        Username.setForeground(new java.awt.Color(153, 153, 153));
        Username.setText("Enter Username");
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameMouseClicked(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        FullName.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        FullName.setForeground(new java.awt.Color(153, 153, 153));
        FullName.setText("Enter Full Name");
        FullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FullNameFocusLost(evt);
            }
        });
        FullName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullNameMouseClicked(evt);
            }
        });
        FullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullNameActionPerformed(evt);
            }
        });

        UsernameLabel.setBackground(new java.awt.Color(153, 153, 153));
        UsernameLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        UsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UsernameLabel.setText("Username (20 Characters) :");

        FullNameLabel.setBackground(new java.awt.Color(153, 153, 153));
        FullNameLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        FullNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FullNameLabel.setText("Full Name (Last Name, First Name M.I.) :");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FullName)
                            .addComponent(Username))
                        .addContainerGap())
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addComponent(FullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FullNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ((AbstractDocument) Age.getDocument()).setDocumentFilter(new LimitedDocumentFilter(2));
        Age.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        Age.setForeground(new java.awt.Color(153, 153, 153));
        Age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Age.setText("00");
        Age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AgeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AgeFocusLost(evt);
            }
        });
        Age.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgeMouseClicked(evt);
            }
        });
        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });

        Nationality.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        Nationality.setForeground(new java.awt.Color(153, 153, 153));
        Nationality.setText("Enter Nationality");
        Nationality.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NationalityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NationalityFocusLost(evt);
            }
        });
        Nationality.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NationalityMouseClicked(evt);
            }
        });
        Nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationalityActionPerformed(evt);
            }
        });

        AgeLabel.setBackground(new java.awt.Color(153, 153, 153));
        AgeLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        AgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AgeLabel.setText("Age : ");

        NationalityLabel.setBackground(new java.awt.Color(153, 153, 153));
        NationalityLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        NationalityLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NationalityLabel.setText("Nationality : ");

        BirthdayDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BirthdayDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BirthdayMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BirthdayMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BirthdayYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BirthdayYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BirthdayYear.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ((AbstractDocument) PhoneNumber.getDocument()).setDocumentFilter(new LimitedDocumentFilter(11));
        PhoneNumber.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        PhoneNumber.setForeground(new java.awt.Color(153, 153, 153));
        PhoneNumber.setText("09123456789");
        PhoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PhoneNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhoneNumberFocusLost(evt);
            }
        });
        PhoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhoneNumberMouseClicked(evt);
            }
        });
        PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberActionPerformed(evt);
            }
        });

        PhoneNumberLabel.setBackground(new java.awt.Color(153, 153, 153));
        PhoneNumberLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        PhoneNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PhoneNumberLabel.setText("Phone Number (11 Digit):");

        BirthdayLabel.setBackground(new java.awt.Color(153, 153, 153));
        BirthdayLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        BirthdayLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BirthdayLabel.setText("Birthdate (MM/DD/YY) : ");

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BirthdayMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BirthdayDay, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BirthdayYear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NationalityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nationality))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneNumber)
                            .addComponent(PhoneNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BirthdayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(BirthdayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BirthdayMonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthdayDay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthdayYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NationalityLabel)
                    .addComponent(PhoneNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Panel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        EmailAddress.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        EmailAddress.setForeground(new java.awt.Color(153, 153, 153));
        EmailAddress.setText("example@email.com");
        EmailAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailAddressFocusLost(evt);
            }
        });
        EmailAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmailAddressMouseClicked(evt);
            }
        });
        EmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailAddressActionPerformed(evt);
            }
        });

        HomeAddress.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        HomeAddress.setForeground(new java.awt.Color(153, 153, 153));
        HomeAddress.setText("123 Mickey Mouse Club House St.");
        HomeAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                HomeAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                HomeAddressFocusLost(evt);
            }
        });
        HomeAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeAddressMouseClicked(evt);
            }
        });
        HomeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeAddressActionPerformed(evt);
            }
        });

        EmailAddressLabel.setBackground(new java.awt.Color(153, 153, 153));
        EmailAddressLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        EmailAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmailAddressLabel.setText("E-Mail Address :");

        HomeAddressLabel.setBackground(new java.awt.Color(153, 153, 153));
        HomeAddressLabel.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        HomeAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeAddressLabel.setText("Home Address :");

        MaritalStatusLabel.setBackground(new java.awt.Color(153, 153, 153));
        MaritalStatusLabel.setFont(new java.awt.Font("Product Sans", 0, 15)); // NOI18N
        MaritalStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaritalStatusLabel.setText("Marital Status :");

        MaritalStatusButtons.add(ButtonSingle);
        ButtonSingle.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        ButtonSingle.setText("Single");
        ButtonSingle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSingleActionPerformed(evt);
            }
        });

        MaritalStatusButtons.add(ButtonMarried);
        ButtonMarried.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        ButtonMarried.setText("Married");
        ButtonMarried.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonMarried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMarriedActionPerformed(evt);
            }
        });

        MaritalStatusButtons.add(ButtonWidowed);
        ButtonWidowed.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        ButtonWidowed.setText("Widowed");
        ButtonWidowed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EmailAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomeAddress)
                    .addComponent(EmailAddress)
                    .addComponent(HomeAddressLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(ButtonSingle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonMarried)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonWidowed)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(MaritalStatusLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EmailAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaritalStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSingle)
                    .addComponent(ButtonMarried)
                    .addComponent(ButtonWidowed))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LogIn.setBackground(new java.awt.Color(204, 255, 255));
        LogIn.setFont(new java.awt.Font("Product Sans", 0, 16)); // NOI18N
        LogIn.setForeground(new java.awt.Color(0, 51, 51));
        LogIn.setText("Log In");
        LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInMouseClicked(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(255, 204, 204));
        Exit.setFont(new java.awt.Font("Product Sans", 0, 16)); // NOI18N
        Exit.setForeground(new java.awt.Color(51, 0, 0));
        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Border2Layout = new javax.swing.GroupLayout(Border2);
        Border2.setLayout(Border2Layout);
        Border2Layout.setHorizontalGroup(
            Border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Border2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Border2Layout.createSequentialGroup()
                        .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Panel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Border2Layout.setVerticalGroup(
            Border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Border2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(Border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Border1Layout = new javax.swing.GroupLayout(Border1);
        Border1.setLayout(Border1Layout);
        Border1Layout.setHorizontalGroup(
            Border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Border1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Border2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Border1Layout.setVerticalGroup(
            Border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Border1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Border2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Border1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Border1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        // TODO add your handling code here:
        if(Username.getText().equals("Enter Username")){
            Username.setForeground(Color.black);
            Username.setText("");
        }
    }//GEN-LAST:event_UsernameFocusGained

    private void UsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameMouseClicked

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void FullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FullNameFocusGained
        if(FullName.getText().equals("Enter Full Name")){
            FullName.setForeground(Color.black);
            FullName.setText("");
        }
    }//GEN-LAST:event_FullNameFocusGained

    private void FullNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FullNameMouseClicked

    private void FullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullNameActionPerformed

    private void AgeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AgeFocusGained
        if(Age.getText().equals("00")){
            Age.setForeground(Color.black);
            Age.setText("");
        }
    }//GEN-LAST:event_AgeFocusGained

    private void AgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeMouseClicked

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void NationalityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NationalityFocusGained
        if(Nationality.getText().equals("Enter Nationality")){
            Nationality.setForeground(Color.black);
            Nationality.setText("");
        }
    }//GEN-LAST:event_NationalityFocusGained

    private void NationalityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NationalityMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NationalityMouseClicked

    private void NationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NationalityActionPerformed

    private void PhoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneNumberFocusGained
        if(PhoneNumber.getText().equals("09123456789")){
            PhoneNumber.setForeground(Color.black);
            PhoneNumber.setText("");
        }
    }//GEN-LAST:event_PhoneNumberFocusGained

    private void PhoneNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhoneNumberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberMouseClicked

    private void PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberActionPerformed

    private void EmailAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailAddressFocusGained
        if(EmailAddress.getText().equals("example@email.com")){
            EmailAddress.setForeground(Color.black);
            EmailAddress.setText("");
        }
    }//GEN-LAST:event_EmailAddressFocusGained

    private void EmailAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailAddressMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailAddressMouseClicked

    private void EmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailAddressActionPerformed

    private void HomeAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HomeAddressFocusGained
        // TODO add your handling code here:
        if(HomeAddress.getText().equals("123 Mickey Mouse Club House St.")){
            HomeAddress.setForeground(Color.black);
            HomeAddress.setText("");
        }
    }//GEN-LAST:event_HomeAddressFocusGained

    private void HomeAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeAddressMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeAddressMouseClicked

    private void HomeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeAddressActionPerformed

    private void ButtonSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSingleActionPerformed

    private void ButtonMarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonMarriedActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
        if (Username.getText().isEmpty()) {
            Username.setText("Enter Username");
            Username.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_UsernameFocusLost

    private void FullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FullNameFocusLost
        if (FullName.getText().isEmpty()) {
            FullName.setText("Enter Full Name");
            FullName.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_FullNameFocusLost

    private void AgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AgeFocusLost
        if (Age.getText().isEmpty()) {
            Age.setText("00");
            Age.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_AgeFocusLost

    private void NationalityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NationalityFocusLost
        if (Nationality.getText().isEmpty()) {
            Nationality.setText("Enter Nationality");
            Nationality.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_NationalityFocusLost

    private void PhoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneNumberFocusLost
        if (PhoneNumber.getText().isEmpty()) {
            PhoneNumber.setText("09123456789");
            PhoneNumber.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_PhoneNumberFocusLost

    private void EmailAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailAddressFocusLost
        if (EmailAddress.getText().isEmpty()) {
            EmailAddress.setText("example@email.com");
            EmailAddress.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_EmailAddressFocusLost

    private void HomeAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HomeAddressFocusLost
        if (HomeAddress.getText().isEmpty()) {
            HomeAddress.setText("123 Mickey Mouse Club House St.");
            HomeAddress.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_HomeAddressFocusLost

    private void LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMouseClicked
        AccountPage accountPage = new AccountPage();
            accountPage.setVisible(true);
            accountPage.setLocationRelativeTo(null);
            
        dispose();
    }//GEN-LAST:event_LogInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JComboBox<String> BirthdayDay;
    private javax.swing.JLabel BirthdayLabel;
    private javax.swing.JComboBox<String> BirthdayMonth;
    private javax.swing.JComboBox<String> BirthdayYear;
    private javax.swing.JPanel Border1;
    private javax.swing.JPanel Border2;
    private javax.swing.JRadioButton ButtonMarried;
    private javax.swing.JRadioButton ButtonSingle;
    private javax.swing.JRadioButton ButtonWidowed;
    private javax.swing.JLabel CreateAccount;
    private javax.swing.JTextField EmailAddress;
    private javax.swing.JLabel EmailAddressLabel;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField FullName;
    private javax.swing.JLabel FullNameLabel;
    private javax.swing.JPanel Header;
    private javax.swing.JTextField HomeAddress;
    private javax.swing.JLabel HomeAddressLabel;
    private javax.swing.JButton LogIn;
    private javax.swing.ButtonGroup MaritalStatusButtons;
    private javax.swing.JLabel MaritalStatusLabel;
    private javax.swing.JTextField Nationality;
    private javax.swing.JLabel NationalityLabel;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel UsernameLabel;
    // End of variables declaration//GEN-END:variables
}
