/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bsrtu.bankingapp;

/**
 *
 * @author Gab
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Back = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        ResetPIN = new javax.swing.JButton();
        ResetPassword = new javax.swing.JButton();
        UsernamePanel = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        ChangeUsername = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        PersonalInformationPanel = new javax.swing.JPanel();
        HomeAddressLabel = new javax.swing.JLabel();
        MaritalStatusLabel = new javax.swing.JLabel();
        NationalityLabel = new javax.swing.JLabel();
        BirthdayLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        PersonalInformationLabel = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        Birthday = new javax.swing.JLabel();
        Nationality = new javax.swing.JLabel();
        MaritalStatus = new javax.swing.JLabel();
        HomeAddress = new javax.swing.JLabel();
        LinkedAccountsPanel = new javax.swing.JPanel();
        LinkedAccountsLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        EmailAddressLabel = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JLabel();
        EmailAddress = new javax.swing.JLabel();
        ChangePhoneNumber = new javax.swing.JButton();
        ChangeEmailAddress = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Back.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        LogOut.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 102, 102));
        LogOut.setText("Log Out");

        ResetPIN.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        ResetPIN.setText("Reset PIN");
        ResetPIN.setContentAreaFilled(false);

        ResetPassword.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        ResetPassword.setText("Reset Password");
        ResetPassword.setContentAreaFilled(false);
        ResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPasswordActionPerformed(evt);
            }
        });

        UsernamePanel.setBackground(java.awt.Color.white);
        UsernamePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        UsernameLabel.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        UsernameLabel.setText("Hello, ");

        ChangeUsername.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        ChangeUsername.setText("Change");
        ChangeUsername.setContentAreaFilled(false);
        ChangeUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeUsernameActionPerformed(evt);
            }
        });

        Username.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        Username.setText("Freaky Bob");

        javax.swing.GroupLayout UsernamePanelLayout = new javax.swing.GroupLayout(UsernamePanel);
        UsernamePanel.setLayout(UsernamePanelLayout);
        UsernamePanelLayout.setHorizontalGroup(
            UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UsernameLabel)
                .addGap(1, 1, 1)
                .addComponent(Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChangeUsername)
                .addContainerGap())
        );
        UsernamePanelLayout.setVerticalGroup(
            UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsernamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel)
                    .addComponent(ChangeUsername)
                    .addComponent(Username))
                .addGap(72, 72, 72))
        );

        PersonalInformationPanel.setBackground(java.awt.Color.white);
        PersonalInformationPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        HomeAddressLabel.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        HomeAddressLabel.setText("Home Address:");

        MaritalStatusLabel.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        MaritalStatusLabel.setText("Marital Status: ");

        NationalityLabel.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        NationalityLabel.setText("Nationality:");

        BirthdayLabel.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        BirthdayLabel.setText("Birthday: ");

        AgeLabel.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        AgeLabel.setText("Age:");

        NameLabel.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        NameLabel.setText("Name: ");

        PersonalInformationLabel.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        PersonalInformationLabel.setText("Personal Information:");

        Name.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        Name.setText("John Pork");

        Age.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        Age.setText("21");

        Birthday.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        Birthday.setText("09 - 11 - 2005");

        Nationality.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        Nationality.setText("African - Indonesian");

        MaritalStatus.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        MaritalStatus.setText("Widowed");

        HomeAddress.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        HomeAddress.setText("132 Oklahoma St. Ohio");

        javax.swing.GroupLayout PersonalInformationPanelLayout = new javax.swing.GroupLayout(PersonalInformationPanel);
        PersonalInformationPanel.setLayout(PersonalInformationPanelLayout);
        PersonalInformationPanelLayout.setHorizontalGroup(
            PersonalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalInformationPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PersonalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PersonalInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PersonalInformationPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PersonalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PersonalInformationPanelLayout.createSequentialGroup()
                                .addComponent(NationalityLabel)
                                .addGap(5, 5, 5)
                                .addComponent(Nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PersonalInformationPanelLayout.createSequentialGroup()
                                .addComponent(AgeLabel)
                                .addGap(5, 5, 5)
                                .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PersonalInformationPanelLayout.createSequentialGroup()
                                .addComponent(NameLabel)
                                .addGap(1, 1, 1)
                                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PersonalInformationPanelLayout.createSequentialGroup()
                                .addComponent(BirthdayLabel)
                                .addGap(1, 1, 1)
                                .addComponent(Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PersonalInformationPanelLayout.createSequentialGroup()
                                .addComponent(MaritalStatusLabel)
                                .addGap(1, 1, 1)
                                .addComponent(MaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PersonalInformationPanelLayout.createSequentialGroup()
                                .addComponent(HomeAddressLabel)
                                .addGap(5, 5, 5)
                                .addComponent(HomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        PersonalInformationPanelLayout.setVerticalGroup(
            PersonalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonalInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PersonalInformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PersonalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(Age))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BirthdayLabel)
                    .addComponent(Birthday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NationalityLabel)
                    .addComponent(Nationality))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaritalStatusLabel)
                    .addComponent(MaritalStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeAddressLabel)
                    .addComponent(HomeAddress))
                .addGap(20, 20, 20))
        );

        LinkedAccountsPanel.setBackground(java.awt.Color.white);
        LinkedAccountsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LinkedAccountsLabel.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        LinkedAccountsLabel.setText("Linked Accounts:");

        PhoneNumberLabel.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        PhoneNumberLabel.setText("Phone Number: ");

        EmailAddressLabel.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        EmailAddressLabel.setText("Email Address: ");

        PhoneNumber.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        PhoneNumber.setText("09132465798");

        EmailAddress.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        EmailAddress.setText("porkjohn01@hotmail.com");

        ChangePhoneNumber.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        ChangePhoneNumber.setText("Change");
        ChangePhoneNumber.setContentAreaFilled(false);
        ChangePhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePhoneNumberActionPerformed(evt);
            }
        });

        ChangeEmailAddress.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        ChangeEmailAddress.setText("Change");
        ChangeEmailAddress.setContentAreaFilled(false);
        ChangeEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeEmailAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LinkedAccountsPanelLayout = new javax.swing.GroupLayout(LinkedAccountsPanel);
        LinkedAccountsPanel.setLayout(LinkedAccountsPanelLayout);
        LinkedAccountsPanelLayout.setHorizontalGroup(
            LinkedAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LinkedAccountsPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(LinkedAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LinkedAccountsPanelLayout.createSequentialGroup()
                        .addComponent(LinkedAccountsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LinkedAccountsPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(LinkedAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailAddressLabel))
                        .addGroup(LinkedAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LinkedAccountsPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(PhoneNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ChangePhoneNumber))
                            .addGroup(LinkedAccountsPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(EmailAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ChangeEmailAddress)))))
                .addContainerGap())
        );
        LinkedAccountsPanelLayout.setVerticalGroup(
            LinkedAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LinkedAccountsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LinkedAccountsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LinkedAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberLabel)
                    .addComponent(ChangePhoneNumber)
                    .addComponent(PhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LinkedAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailAddressLabel)
                    .addComponent(ChangeEmailAddress)
                    .addComponent(EmailAddress))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LinkedAccountsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PersonalInformationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ResetPassword)
                            .addComponent(UsernamePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ResetPIN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogOut)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PersonalInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LinkedAccountsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResetPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResetPIN)
                    .addComponent(LogOut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangePhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePhoneNumberActionPerformed

    private void ChangeEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeEmailAddressActionPerformed

    private void ResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetPasswordActionPerformed

    private void ChangeUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeUsernameActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        AccountPage accountPage = new AccountPage();
        accountPage.setVisible(true);
        accountPage.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Birthday;
    private javax.swing.JLabel BirthdayLabel;
    private javax.swing.JButton ChangeEmailAddress;
    private javax.swing.JButton ChangePhoneNumber;
    private javax.swing.JButton ChangeUsername;
    private javax.swing.JLabel EmailAddress;
    private javax.swing.JLabel EmailAddressLabel;
    private javax.swing.JLabel HomeAddress;
    private javax.swing.JLabel HomeAddressLabel;
    private javax.swing.JLabel LinkedAccountsLabel;
    private javax.swing.JPanel LinkedAccountsPanel;
    private javax.swing.JLabel LogOut;
    private javax.swing.JLabel MaritalStatus;
    private javax.swing.JLabel MaritalStatusLabel;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel Nationality;
    private javax.swing.JLabel NationalityLabel;
    private javax.swing.JLabel PersonalInformationLabel;
    private javax.swing.JPanel PersonalInformationPanel;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JButton ResetPIN;
    private javax.swing.JButton ResetPassword;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JPanel UsernamePanel;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
